language: python
python:
  - "3.4"
install: "pip install -r requirements.txt --use-mirrors"
script: py.test
notifications:
  email:
    recipients:
      - code@iatistandard.org
    on_success: change
    on_failure: always
